# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apis/apis_rs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61pis/apis_rs.proto\x12\x0bprofile.api\"5\n\x10UserInfoResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\"W\n\x0fUserInfoRequest\x12\x14\n\x07user_id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x15\n\x08username\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_user_idB\x0b\n\t_username\"7\n\x14\x41\x63tivateUserResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x13\x41\x63tivateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\"\'\n\x14\x42\x61tchUserInfoRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\")\n\x15\x42\x61tchUserInfoResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"+\n\x18\x42\x61tchFollowStatusRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"-\n\x19\x42\x61tchFollowStatusResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xeb\x02\n\x07Profile\x12I\n\x08UserInfo\x12\x1c.profile.api.UserInfoRequest\x1a\x1d.profile.api.UserInfoResponse\"\x00\x12X\n\rBatchUserInfo\x12!.profile.api.BatchUserInfoRequest\x1a\".profile.api.BatchUserInfoResponse\"\x00\x12U\n\x0c\x41\x63tivateUser\x12 .profile.api.ActivateUserRequest\x1a!.profile.api.ActivateUserResponse\"\x00\x12\x64\n\x11\x42\x61tchFollowStatus\x12%.profile.api.BatchFollowStatusRequest\x1a&.profile.api.BatchFollowStatusResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apis.apis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINFORESPONSE._serialized_start=32
  _USERINFORESPONSE._serialized_end=85
  _USERINFOREQUEST._serialized_start=87
  _USERINFOREQUEST._serialized_end=174
  _ACTIVATEUSERRESPONSE._serialized_start=176
  _ACTIVATEUSERRESPONSE._serialized_end=231
  _ACTIVATEUSERREQUEST._serialized_start=233
  _ACTIVATEUSERREQUEST._serialized_end=290
  _BATCHUSERINFOREQUEST._serialized_start=292
  _BATCHUSERINFOREQUEST._serialized_end=331
  _BATCHUSERINFORESPONSE._serialized_start=333
  _BATCHUSERINFORESPONSE._serialized_end=374
  _BATCHFOLLOWSTATUSREQUEST._serialized_start=376
  _BATCHFOLLOWSTATUSREQUEST._serialized_end=419
  _BATCHFOLLOWSTATUSRESPONSE._serialized_start=421
  _BATCHFOLLOWSTATUSRESPONSE._serialized_end=466
  _PROFILE._serialized_start=469
  _PROFILE._serialized_end=832
# @@protoc_insertion_point(module_scope)
