# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apis import apis_rs_pb2 as apis_dot_apis__rs__pb2


class TestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestFunc = channel.unary_unary(
                '/test_service.api.TestService/TestFunc',
                request_serializer=apis_dot_apis__rs__pb2.TestFuncRequest.SerializeToString,
                response_deserializer=apis_dot_apis__rs__pb2.TestFuncResponse.FromString,
                )


class TestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TestFunc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestFunc': grpc.unary_unary_rpc_method_handler(
                    servicer.TestFunc,
                    request_deserializer=apis_dot_apis__rs__pb2.TestFuncRequest.FromString,
                    response_serializer=apis_dot_apis__rs__pb2.TestFuncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test_service.api.TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestFunc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test_service.api.TestService/TestFunc',
            apis_dot_apis__rs__pb2.TestFuncRequest.SerializeToString,
            apis_dot_apis__rs__pb2.TestFuncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
