# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apis/apis_rs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61pis/apis_rs.proto\x12\x10test_service.api\",\n\x10TestFuncResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"E\n\x0fTestFuncRequest\x12\x0f\n\x02id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_name2b\n\x0bTestService\x12S\n\x08TestFunc\x12!.test_service.api.TestFuncRequest\x1a\".test_service.api.TestFuncResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apis.apis_rs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTFUNCRESPONSE._serialized_start=40
  _TESTFUNCRESPONSE._serialized_end=84
  _TESTFUNCREQUEST._serialized_start=86
  _TESTFUNCREQUEST._serialized_end=155
  _TESTSERVICE._serialized_start=157
  _TESTSERVICE._serialized_end=255
# @@protoc_insertion_point(module_scope)
